version '3.8'

services:
    postfres:
      image: postgres-15-alpine
      container_name: biblioteca-db
      ports:
        - "5432:5432""
      environment:
        - POSTGRES_DB=biblioteca-db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=senha_secreta
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

