spring:
  application:
    name: biblioteca
  datasource:
    url: jbc:postgresql://localhost:5432/biblioteca_db
    username: admin
    password: senha_secreta
  jpa:
    hibernate:
      ddl-auto: update # Cria tabelas sozinho
      show-sql: true
  management:
    endpoint:
      web:
        exposure:
          include: health, info, metrics, prometheus
    endpoints:
      health:
        show-details: always